package resourceLoaders;

import javax.swing.ImageIcon;

public enum ImageName {
    MENU_BACKGROUND, MENU_BACKGROUND_BLURRY, ARENACARD_EMPTY, TOWER, SPOT_LEFT, SPOT_TOWER,TOWER_CARD, GAMEBOARD_RIGHT,
    HERO_FRONT_EMPTY_TALL, HEART_ACTIVATED, HEART_DEACTIVATED, ACTION_ACTIVATED, ACTION_DEACTIVATED, DELAY,
    HIDEOUT_CARD, SPOT_RIGHT, SPOT_HIDEOUT, GAMEBOARD_EMPTY, TOWER_AIM, BUTTON, AVATAR_BALTHUR_DEACTIVATED,
    AVATAR_DAHLIA_DEACTIVATED, AVATAR_FLINT_DEACTIVATED, AVATAR_TOLPAN_DEACTIVATED, AVATAR_WOROK_DEACTIVATED,
    AVATAR_BALTHUR, AVATAR_DAHLIA, AVATAR_FLINT, AVATAR_TOLPAN, AVATAR_WOROK, MAPICON_BALTHUR, MAPICON_DAHLIA,
    MAPICON_FLINT, MAPICON_TOLPAN, MAPICON_WOROK, GRAVESTONE_BALTHUR, GRAVESTONE_DAHLIA,
    GRAVESTONE_FLINT, GRAVESTONE_TOLPAN, GRAVESTONE_WOROK,GAMEBOARD_INSTRUCTION, HEROPROTECTION_SYMBOL
}
