package resourceLoaders;

import javax.swing.ImageIcon;

public enum ImageName {
	MENU_BACKGROUND, MENU_BACKGROUND_BLURRY, ARENACARD_EMPTY, TOWER, SPOT_LEFT, SPOT_TOWER, GAMEBOARD_RIGHT,
	HERO_FRONT_EMPTY_TALL, HEART_ACTIVATED, HEART_DEACTIVATED, ACTION_ACTIVATED, ACTION_DEACTIVATED, DELAY,
	HIDEOUT_CARD, SPOT_RIGHT,SPOT_HIDEOUT,GAMEBOARD_EMPTY,TOWER_AIM,BUTTON
}
